//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatlabuhApp.Properties.Resourses.Text {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class uk_UA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal uk_UA() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatlabuhApp.Properties.Resourses.Text.uk-UA", typeof(uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Водний баланс.
        /// </summary>
        internal static string CalculationPartNameText1 {
            get {
                return ResourceManager.GetString("CalculationPartNameText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сольовий баланс.
        /// </summary>
        internal static string CalculationPartNameText2 {
            get {
                return ResourceManager.GetString("CalculationPartNameText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витратна частина.
        /// </summary>
        internal static string CalculationPartNameText3 {
            get {
                return ResourceManager.GetString("CalculationPartNameText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибуткова частина.
        /// </summary>
        internal static string CalculationPartNameText4 {
            get {
                return ResourceManager.GetString("CalculationPartNameText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити нову діаграму.
        /// </summary>
        internal static string ChartViewToolItemText1 {
            get {
                return ResourceManager.GetString("ChartViewToolItemText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти як зображення.
        /// </summary>
        internal static string ChartViewToolItemText2 {
            get {
                return ResourceManager.GetString("ChartViewToolItemText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відкрити в окремому вікні.
        /// </summary>
        internal static string ChartViewToolItemText3 {
            get {
                return ResourceManager.GetString("ChartViewToolItemText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва діаграми.
        /// </summary>
        internal static string ChartViewToolItemText4 {
            get {
                return ResourceManager.GetString("ChartViewToolItemText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип діаграми.
        /// </summary>
        internal static string ChartViewToolItemText5 {
            get {
                return ResourceManager.GetString("ChartViewToolItemText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підписи вісей.
        /// </summary>
        internal static string ChartViewToolItemText6 {
            get {
                return ResourceManager.GetString("ChartViewToolItemText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показати сітку.
        /// </summary>
        internal static string ChartViewToolItemText7 {
            get {
                return ResourceManager.GetString("ChartViewToolItemText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкажіть рік розрахунку:.
        /// </summary>
        internal static string ComboBoxText1 {
            get {
                return ResourceManager.GetString("ComboBoxText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перерахувати розрахунок.
        /// </summary>
        internal static string ContextMenuText1 {
            get {
                return ResourceManager.GetString("ContextMenuText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти зміни.
        /// </summary>
        internal static string ContextMenuText2 {
            get {
                return ResourceManager.GetString("ContextMenuText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити розрахунок.
        /// </summary>
        internal static string ContextMenuText3 {
            get {
                return ResourceManager.GetString("ContextMenuText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повернутися.
        /// </summary>
        internal static string CreateCalculationButtonText1 {
            get {
                return ResourceManager.GetString("CreateCalculationButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти вихідні дані.
        /// </summary>
        internal static string CreateCalculationButtonText2 {
            get {
                return ResourceManager.GetString("CreateCalculationButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провести розрахунок.
        /// </summary>
        internal static string CreateCalculationButtonText3 {
            get {
                return ResourceManager.GetString("CreateCalculationButtonText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистити поля.
        /// </summary>
        internal static string CreateCalculationButtonText4 {
            get {
                return ResourceManager.GetString("CreateCalculationButtonText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматичне заповнення.
        /// </summary>
        internal static string CreateCalculationCheckText1 {
            get {
                return ResourceManager.GetString("CreateCalculationCheckText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкажіть рівні води.
        /// </summary>
        internal static string CreateCalculationGroupText1 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкажіть визначення випаровування.
        /// </summary>
        internal static string CreateCalculationGroupText10 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкажіть збір води на зрошування.
        /// </summary>
        internal static string CreateCalculationGroupText2 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума опадів за місяцб по м/ст Ізмаїл.
        /// </summary>
        internal static string CreateCalculationGroupText3 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть випаровування м/ст Болград.
        /// </summary>
        internal static string CreateCalculationGroupText4 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть дефіцит вологості.
        /// </summary>
        internal static string CreateCalculationGroupText5 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Графік роботи шлюзів.
        /// </summary>
        internal static string CreateCalculationGroupText6 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наповнення озера.
        /// </summary>
        internal static string CreateCalculationGroupText7 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скиди води в озеро.
        /// </summary>
        internal static string CreateCalculationGroupText8 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкажіть об&apos;єми за рік.
        /// </summary>
        internal static string CreateCalculationGroupText9 {
            get {
                return ResourceManager.GetString("CreateCalculationGroupText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вказати дані з графіка роботи шлюзів.
        /// </summary>
        internal static string CreateCalculationLabelText1 {
            get {
                return ResourceManager.GetString("CreateCalculationLabelText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приплив ґрунтових вод:.
        /// </summary>
        internal static string CreateCalculationLabelText2 {
            get {
                return ResourceManager.GetString("CreateCalculationLabelText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кінець груд. поперед. року:.
        /// </summary>
        internal static string CreateCalculationLabelText3 {
            get {
                return ResourceManager.GetString("CreateCalculationLabelText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані з м/ст Болград.
        /// </summary>
        internal static string CreateCalculationRadioText1 {
            get {
                return ResourceManager.GetString("CreateCalculationRadioText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розрахувати.
        /// </summary>
        internal static string CreateCalculationRadioText2 {
            get {
                return ResourceManager.GetString("CreateCalculationRadioText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вести велечини.
        /// </summary>
        internal static string CreateCalculationRadioText3 {
            get {
                return ResourceManager.GetString("CreateCalculationRadioText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мБС.
        /// </summary>
        internal static string MeasurementMeasures1 {
            get {
                return ResourceManager.GetString("MeasurementMeasures1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на млн. м^3.
        /// </summary>
        internal static string MeasurementMeasures2 {
            get {
                return ResourceManager.GetString("MeasurementMeasures2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на км^2.
        /// </summary>
        internal static string MeasurementMeasures3 {
            get {
                return ResourceManager.GetString("MeasurementMeasures3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мм.
        /// </summary>
        internal static string MeasurementMeasures4 {
            get {
                return ResourceManager.GetString("MeasurementMeasures4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на гПа.
        /// </summary>
        internal static string MeasurementMeasures5 {
            get {
                return ResourceManager.GetString("MeasurementMeasures5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кг/м^3.
        /// </summary>
        internal static string MeasurementMeasures6 {
            get {
                return ResourceManager.GetString("MeasurementMeasures6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10^6 т..
        /// </summary>
        internal static string MeasurementMeasures7 {
            get {
                return ResourceManager.GetString("MeasurementMeasures7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити новий розрахунок.
        /// </summary>
        internal static string MenuItemText1 {
            get {
                return ResourceManager.GetString("MenuItemText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переглянути розрахунки.
        /// </summary>
        internal static string MenuItemText2 {
            get {
                return ResourceManager.GetString("MenuItemText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відправити в Excel.
        /// </summary>
        internal static string MenuItemText3 {
            get {
                return ResourceManager.GetString("MenuItemText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переглянути довідку.
        /// </summary>
        internal static string MenuItemText4 {
            get {
                return ResourceManager.GetString("MenuItemText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Про програму.
        /// </summary>
        internal static string MenuItemText5 {
            get {
                return ResourceManager.GetString("MenuItemText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розрахунки.
        /// </summary>
        internal static string MenuText1 {
            get {
                return ResourceManager.GetString("MenuText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Діаграми.
        /// </summary>
        internal static string MenuText2 {
            get {
                return ResourceManager.GetString("MenuText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налаштування.
        /// </summary>
        internal static string MenuText3 {
            get {
                return ResourceManager.GetString("MenuText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        internal static string MenuText4 {
            get {
                return ResourceManager.GetString("MenuText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Місяць.
        /// </summary>
        internal static string MonthText {
            get {
                return ResourceManager.GetString("MonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Січ..
        /// </summary>
        internal static string MonthText1 {
            get {
                return ResourceManager.GetString("MonthText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жовт..
        /// </summary>
        internal static string MonthText10 {
            get {
                return ResourceManager.GetString("MonthText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Листоп..
        /// </summary>
        internal static string MonthText11 {
            get {
                return ResourceManager.GetString("MonthText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груд..
        /// </summary>
        internal static string MonthText12 {
            get {
                return ResourceManager.GetString("MonthText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лют..
        /// </summary>
        internal static string MonthText2 {
            get {
                return ResourceManager.GetString("MonthText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Берез..
        /// </summary>
        internal static string MonthText3 {
            get {
                return ResourceManager.GetString("MonthText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квіт..
        /// </summary>
        internal static string MonthText4 {
            get {
                return ResourceManager.GetString("MonthText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трав..
        /// </summary>
        internal static string MonthText5 {
            get {
                return ResourceManager.GetString("MonthText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Черв..
        /// </summary>
        internal static string MonthText6 {
            get {
                return ResourceManager.GetString("MonthText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лип..
        /// </summary>
        internal static string MonthText7 {
            get {
                return ResourceManager.GetString("MonthText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серп..
        /// </summary>
        internal static string MonthText8 {
            get {
                return ResourceManager.GetString("MonthText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вер..
        /// </summary>
        internal static string MonthText9 {
            get {
                return ResourceManager.GetString("MonthText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація збору води на зрошування.
        /// </summary>
        internal static string SBCPText1 {
            get {
                return ResourceManager.GetString("SBCPText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація скидів води у р. Дунай.
        /// </summary>
        internal static string SBCPText2 {
            get {
                return ResourceManager.GetString("SBCPText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація води на підтримку рівнів  води в системі озер Лунг-Сафьян.
        /// </summary>
        internal static string SBCPText3 {
            get {
                return ResourceManager.GetString("SBCPText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Втрата солей з фільтрацією.
        /// </summary>
        internal static string SBCPText4 {
            get {
                return ResourceManager.GetString("SBCPText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Втрата солей на зрошуванні.
        /// </summary>
        internal static string SBCPText5 {
            get {
                return ResourceManager.GetString("SBCPText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скиди води разом із солями у р. Дунай.
        /// </summary>
        internal static string SBCPText6 {
            get {
                return ResourceManager.GetString("SBCPText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солі, що виводяться з воддою на підтримку рівнів води у системі озер Лунг-Сафьян.
        /// </summary>
        internal static string SBCPText7 {
            get {
                return ResourceManager.GetString("SBCPText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума витратної частини.
        /// </summary>
        internal static string SBCPText8 {
            get {
                return ResourceManager.GetString("SBCPText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Середня по озеру мінералізація на початку місяця.
        /// </summary>
        internal static string SBPPText1 {
            get {
                return ResourceManager.GetString("SBPPText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Концентрація солей по озеру наприкінці місяця.
        /// </summary>
        internal static string SBPPText10 {
            get {
                return ResourceManager.GetString("SBPPText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надходження солей з опадами.
        /// </summary>
        internal static string SBPPText11 {
            get {
                return ResourceManager.GetString("SBPPText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надходження солей з поверхневим стоком.
        /// </summary>
        internal static string SBPPText12 {
            get {
                return ResourceManager.GetString("SBPPText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надходження солей з бічним припливом.
        /// </summary>
        internal static string SBPPText13 {
            get {
                return ResourceManager.GetString("SBPPText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надходження солей з ґрунтовими водами.
        /// </summary>
        internal static string SBPPText14 {
            get {
                return ResourceManager.GetString("SBPPText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надходження солей з дренажними водами.
        /// </summary>
        internal static string SBPPText15 {
            get {
                return ResourceManager.GetString("SBPPText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надходження солей з Дунайською водою.
        /// </summary>
        internal static string SBPPText16 {
            get {
                return ResourceManager.GetString("SBPPText16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума прихідної частини.
        /// </summary>
        internal static string SBPPText18 {
            get {
                return ResourceManager.GetString("SBPPText18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Середня по озеру мінералізація наприкінці місяця.
        /// </summary>
        internal static string SBPPText2 {
            get {
                return ResourceManager.GetString("SBPPText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація атмосферних опадів.
        /// </summary>
        internal static string SBPPText3 {
            get {
                return ResourceManager.GetString("SBPPText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація поверхневого стоку.
        /// </summary>
        internal static string SBPPText4 {
            get {
                return ResourceManager.GetString("SBPPText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація бічного припливу.
        /// </summary>
        internal static string SBPPText5 {
            get {
                return ResourceManager.GetString("SBPPText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація ґрунтового стоку.
        /// </summary>
        internal static string SBPPText6 {
            get {
                return ResourceManager.GetString("SBPPText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація дренажних вод.
        /// </summary>
        internal static string SBPPText7 {
            get {
                return ResourceManager.GetString("SBPPText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мінералізація Дунайської води.
        /// </summary>
        internal static string SBPPText8 {
            get {
                return ResourceManager.GetString("SBPPText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Концентрація солей по озеру на початку місяця.
        /// </summary>
        internal static string SBPPText9 {
            get {
                return ResourceManager.GetString("SBPPText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати.
        /// </summary>
        internal static string SetupChartButtonText1 {
            get {
                return ResourceManager.GetString("SetupChartButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити.
        /// </summary>
        internal static string SetupChartButtonText2 {
            get {
                return ResourceManager.GetString("SetupChartButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистити.
        /// </summary>
        internal static string SetupChartButtonText3 {
            get {
                return ResourceManager.GetString("SetupChartButtonText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Побудувати.
        /// </summary>
        internal static string SetupChartButtonText4 {
            get {
                return ResourceManager.GetString("SetupChartButtonText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відміна.
        /// </summary>
        internal static string SetupChartButtonText5 {
            get {
                return ResourceManager.GetString("SetupChartButtonText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оберіть рік.
        /// </summary>
        internal static string SetupChartComboText1 {
            get {
                return ResourceManager.GetString("SetupChartComboText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Від.
        /// </summary>
        internal static string SetupChartComboText2 {
            get {
                return ResourceManager.GetString("SetupChartComboText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До.
        /// </summary>
        internal static string SetupChartComboText3 {
            get {
                return ResourceManager.GetString("SetupChartComboText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вісь.
        /// </summary>
        internal static string SetupChartGroupText1 {
            get {
                return ResourceManager.GetString("SetupChartGroupText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкажіть параметри для вісі .
        /// </summary>
        internal static string SetupChartGroupText2 {
            get {
                return ResourceManager.GetString("SetupChartGroupText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Діаграма.
        /// </summary>
        internal static string SetupChartGroupText3 {
            get {
                return ResourceManager.GetString("SetupChartGroupText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роки.
        /// </summary>
        internal static string SetupChartRadioText1 {
            get {
                return ResourceManager.GetString("SetupChartRadioText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Місяці.
        /// </summary>
        internal static string SetupChartRadioText2 {
            get {
                return ResourceManager.GetString("SetupChartRadioText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВБПЧ.
        /// </summary>
        internal static string SetupChartTabText1 {
            get {
                return ResourceManager.GetString("SetupChartTabText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВБВЧ.
        /// </summary>
        internal static string SetupChartTabText2 {
            get {
                return ResourceManager.GetString("SetupChartTabText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СБПЧ.
        /// </summary>
        internal static string SetupChartTabText3 {
            get {
                return ResourceManager.GetString("SetupChartTabText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СБВЧ.
        /// </summary>
        internal static string SetupChartTabText4 {
            get {
                return ResourceManager.GetString("SetupChartTabText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вказати рік.
        /// </summary>
        internal static string SetupChartTabText5 {
            get {
                return ResourceManager.GetString("SetupChartTabText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вказати діапазон.
        /// </summary>
        internal static string SetupChartTabText6 {
            get {
                return ResourceManager.GetString("SetupChartTabText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перегляд розрахунків.
        /// </summary>
        internal static string StatusText1 {
            get {
                return ResourceManager.GetString("StatusText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перегляд налаштувань розрахунку.
        /// </summary>
        internal static string StatusText2 {
            get {
                return ResourceManager.GetString("StatusText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перегляд графіку.
        /// </summary>
        internal static string StatusText3 {
            get {
                return ResourceManager.GetString("StatusText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відравка розрахунку до Excel:.
        /// </summary>
        internal static string StatusText4 {
            get {
                return ResourceManager.GetString("StatusText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутрішньорічний розподіл поверхневого стоку.
        /// </summary>
        internal static string TableNameText1 {
            get {
                return ResourceManager.GetString("TableNameText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутрішньорічний розподіл припливу ґрунтових вод.
        /// </summary>
        internal static string TableNameText2 {
            get {
                return ResourceManager.GetString("TableNameText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Водний і сольовий баланси озера Катлабух.
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Багатоводний.
        /// </summary>
        internal static string WaterLevelText1 {
            get {
                return ResourceManager.GetString("WaterLevelText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средньоводний.
        /// </summary>
        internal static string WaterLevelText2 {
            get {
                return ResourceManager.GetString("WaterLevelText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маловодний.
        /// </summary>
        internal static string WaterLevelText3 {
            get {
                return ResourceManager.GetString("WaterLevelText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дуже маловодний.
        /// </summary>
        internal static string WaterLevelText4 {
            get {
                return ResourceManager.GetString("WaterLevelText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дефіцит вологості.
        /// </summary>
        internal static string WBCPText1 {
            get {
                return ResourceManager.GetString("WBCPText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума витратної частини.
        /// </summary>
        internal static string WBCPText10 {
            get {
                return ResourceManager.GetString("WBCPText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скиди води з озера в р. Дунай.
        /// </summary>
        internal static string WBCPText11 {
            get {
                return ResourceManager.GetString("WBCPText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підтримка рівнів води озер Лунг-Сафьян.
        /// </summary>
        internal static string WBCPText12 {
            get {
                return ResourceManager.GetString("WBCPText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логарифм дефіциту вологості.
        /// </summary>
        internal static string WBCPText2 {
            get {
                return ResourceManager.GetString("WBCPText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логарифим випаровування.
        /// </summary>
        internal static string WBCPText3 {
            get {
                return ResourceManager.GetString("WBCPText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Випаровування.
        /// </summary>
        internal static string WBCPText4 {
            get {
                return ResourceManager.GetString("WBCPText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транспірація.
        /// </summary>
        internal static string WBCPText5 {
            get {
                return ResourceManager.GetString("WBCPText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм випаровування.
        /// </summary>
        internal static string WBCPText6 {
            get {
                return ResourceManager.GetString("WBCPText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм транспірації.
        /// </summary>
        internal static string WBCPText7 {
            get {
                return ResourceManager.GetString("WBCPText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм фільтрації.
        /// </summary>
        internal static string WBCPText8 {
            get {
                return ResourceManager.GetString("WBCPText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Збір води на зрошування.
        /// </summary>
        internal static string WBCPText9 {
            get {
                return ResourceManager.GetString("WBCPText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рівень води на початку місяця.
        /// </summary>
        internal static string WBPPText1 {
            get {
                return ResourceManager.GetString("WBPPText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм річкового стоку.
        /// </summary>
        internal static string WBPPText10 {
            get {
                return ResourceManager.GetString("WBPPText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм бічного припливу.
        /// </summary>
        internal static string WBPPText11 {
            get {
                return ResourceManager.GetString("WBPPText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм припливу ґрунтових вод.
        /// </summary>
        internal static string WBPPText12 {
            get {
                return ResourceManager.GetString("WBPPText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм надходження дренажних вод.
        /// </summary>
        internal static string WBPPText13 {
            get {
                return ResourceManager.GetString("WBPPText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума прихідної частини.
        /// </summary>
        internal static string WBPPText14 {
            get {
                return ResourceManager.GetString("WBPPText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приплив води з р. Дунай.
        /// </summary>
        internal static string WBPPText15 {
            get {
                return ResourceManager.GetString("WBPPText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нев&apos;язкі рівняння водного балансу.
        /// </summary>
        internal static string WBPPText16 {
            get {
                return ResourceManager.GetString("WBPPText16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рівень води наприкінці місяця.
        /// </summary>
        internal static string WBPPText2 {
            get {
                return ResourceManager.GetString("WBPPText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Середній рівень води за місяць.
        /// </summary>
        internal static string WBPPText3 {
            get {
                return ResourceManager.GetString("WBPPText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм води в озері на початку місяця.
        /// </summary>
        internal static string WBPPText4 {
            get {
                return ResourceManager.GetString("WBPPText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм води в озері наприкінці місяця.
        /// </summary>
        internal static string WBPPText5 {
            get {
                return ResourceManager.GetString("WBPPText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зміни об&apos;єму води в озері за місяць.
        /// </summary>
        internal static string WBPPText6 {
            get {
                return ResourceManager.GetString("WBPPText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Площа водного дзеркала.
        /// </summary>
        internal static string WBPPText7 {
            get {
                return ResourceManager.GetString("WBPPText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опади виміряні на м/ст Ізмаїл.
        /// </summary>
        internal static string WBPPText8 {
            get {
                return ResourceManager.GetString("WBPPText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єм атмосферних опадів.
        /// </summary>
        internal static string WBPPText9 {
            get {
                return ResourceManager.GetString("WBPPText9", resourceCulture);
            }
        }
    }
}
